- src/plugins/remote-cache/storage/s3.ts
- test/vercel.ts
Same as #37 but with fallbacks for Vercel.
> fix: don't require AWS env vars

- src/plugins/remote-cache/index.ts
- src/plugins/remote-cache/routes/head-artifact.ts
- src/plugins/remote-cache/routes/index.ts
- src/plugins/remote-cache/storage/index.ts
- test/google-cloud-storage.ts
- test/local.ts
- test/s3.ts
Turbo repo introduce support for `dry-run` to inspect caches and report on whether a cache entry in the local and/or remote cache exists for a given hash.   In order to leverage, remote cache implementors must implement a HEAD route to check for the resource.  This PR enables this.
See the following for references..
https://github.com/vercel/turborepo/issues/1437
https://github.com/vercel/turborepo/pull/1988
and this article for use cases on leveraging this new info reported by dry-run.
https://medium.com/@sppatel/maximizing-job-parallelization-in-ci-workflows-with-jest-and-turborepo-da86b9be0ee6
> chore: head support

- src/plugins/remote-cache/index.ts
The following error occurs because GCS_PRIVATE_KEY cannot be read correctly due to `\n` being escaped when reading values from environment variables.
The following link is helpful for this problem.
this issueshttps://github.com/googleapis/google-auth-library-nodejs/issues/1456#issuecomment-1240270318
> fix: Fixed problem with GCS_PRIVATE_KEY being escaped and causing an error

- docs/supported-storage-providers.md
- package-lock.json
- package.json
- src/plugins/remote-cache/storage/google-cloud-storage.ts
- test/.env.google-cloud-storage.adc
- test/google-cloud-storage.ts
From [docs](https://cloud.google.com/docs/authentication/application-default-credentials):
>ADC is a strategy used by [Cloud Client Libraries and Google API Client Libraries](https://cloud.google.com/apis/docs/client-libraries-explained) to automatically find credentials based on the application environment, and use those credentials to authenticate to Google Cloud APIs. When you set up ADC and use a client library, your code can run in either a development or production environment without changing how your application authenticates to Google Cloud services and APIs.
>    ADC searches for credentials in the following locations:
>    [GOOGLE_APPLICATION_CREDENTIALS environment variable](https://cloud.google.com/docs/authentication/application-default-credentials#GAC)
>    [User …
> Feat/Application Default Credentials GCP auth

- docs/custom-remote-caching.md
- Removes need for defining the VERCEL_* envs since the PR to fix this was merged by the Vercel team a few months ago
- https://github.com/ducktors/turborepo-remote-cache/issues/34#issuecomment-1183651684
- https://github.com/vercel/turbo/pull/1527
> fix: remove need for VERCEL_*

- docs/supported-storage-providers.md
- src/plugins/remote-cache/storage/s3.ts
This PR allows the S3 storage provider to use an `AWS_SESSION_TOKEN` if this has been set in the current environment. This is a non-breaking change.
*Note - this is the same kind of functionality that @wdalmijn was looking to implement in #36, but as this has been open for a few months and appears to have outstanding conflicts with the new codebase I started from a new fork. This is also a smaller change as there probably isn't a need for users to set this manually.*
This is required to run the server in an AWS Lambda Function. Unlike a long running server, the Lambda Function generates temporary credentials to allow the handler to access other AWS resources, and uses the `AWS_SESSION_TOKEN` to achieve this. Without passing this token any calls made via the sdk will fail.
This change just …
> feat: use AWS_SESSION_TOKEN

- tsconfig.json
Sorry for a bunch of PRs to review, I only thought of this small addition late on! 
Non-breaking change. Emits `d.ts` files in build. This makes writing a proxy for the server nicer for typescript users.
Closes #88
- #88
> feat: Emit d.ts files in build

- docs/custom-remote-caching.md
- docs/deployment-environments.md
- docs/index.md
- docs/running-in-lambda.md
- package.json
- pnpm-lock.yaml
- src/aws-lambda.ts
A guide on how to run the `turborepo-remote-cache` server in an AWS Lambda Function.
Credit to @cpitt for a starting point on the handler code in #28.
This is dependant on #86 - as this change is required to allow the Lambda's temporary credentials to access the S3 bucket.
- #28
> feat: how to run in aws lambda

- docs/deployment-environments.md
- docs/running-in-lambda.md
Some minor fixes to the docs I noticed after they were converted to Jekyll: 
- The values of the environment variables on the `Running in Lambda` page are being converted to HTML tags :man_facepalming:, changed these to italics makes sure they display
- Disabled the Table of Contents from being auto-generated at the bottom of the `Deployment Environments` page, it's not necessary
- And removed an erroneous newline I seem to have managed to introduce into the `Deploy to DO` button (the button continues to render and work, but the newline shouldn't be there)
> fix: minor doc fixes

- package.json
- pnpm-lock.yaml
- [Update Fastify from 3.25.0 to 3.29.4](https://github.com/ducktors/turborepo-remote-cache/security/dependabot/5
)
> Fastify: Incorrect Content-Type parsing can lead to CSRF attack 

- docs/supported-storage-providers.md
docs(gcs): Storage Object Admin is required but not mentioned
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- https://github.com/ducktors/turborepo-remote-cache/issues/95
> docs(gcs): role Storage Object Admin is required but not mentioned

- .github/workflows/ci.yml
- package.json
- This update addresses issues with installing packages using npm or yarn on Node versions below 18.
- https://github.com/ducktors/turborepo-remote-cache/issues/178
> fix: remove pnpm from package engine

- docs/running-in-lambda.md
- update docs to use an AWS Lambda function url instead of the API Gateway HTTP API
Function URLs are much simpler to setup and work the same way as the setup with the HTTP API. The request and response event formats follow the same schema as the Amazon API Gateway payload format version 2.0, see [AWS docs](https://docs.aws.amazon.com/lambda/latest/dg/urls-invocation.html).
I've setup an AWS CDK construct to quickly create such configuration, it's already published to npm/constructs.dev, see [cdk-turborepo-remote-cache](https://github.com/NimmLor/cdk-turborepo-remote-cache)
> docs: update lambda docs to use function urls

- README.md
- docs/index.md
Hi, I noticed that in the docs, the URLs were pointing to:
https://turborepo.org/docs/features/remote-caching#custom-remote-caches
whereas now its:
https://turbo.build/repo/docs/core-concepts/remote-caching#self-hosting
Thanks for all the awesome work on this project :)
- None
> docs: Update URLs referring to Turborepo custom remote cache server

- docs/custom-remote-caching.md
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- https://github.com/ducktors/turborepo-remote-cache/issues/
- https://github.com/ducktors/turborepo-remote-cache/issues/
> fix(docs): use recommended docker config for remote cache

- docs/custom-remote-caching.md
- src/plugins/remote-cache/routes/get-artifact.ts
- src/plugins/remote-cache/routes/head-artifact.ts
- src/plugins/remote-cache/routes/put-artifact.ts
- src/plugins/remote-cache/routes/schema.ts
- src/plugins/remote-cache/storage/index.ts
- test/azure-blob-storage.ts
- test/google-cloud-storage.ts
- test/local.ts
- test/minio.ts
- test/s3.ts
Use team over teamId
Ref : https://github.com/vercel/turbo/issues/6765
> fix: Turbos api now uses team instead of teamId

- package.json
- pnpm-lock.yaml
- src/plugins/remote-cache/storage/azure-blob-storage.ts
- src/plugins/remote-cache/storage/index.ts
- test/azure-blob-storage.ts
- Legacy `azure-storage` library was replaced with `@azure/storage-blob`. 
- azure-blob-storage module tests were refactored. The previous implementation had the tests that were dependent on each other and failed if you changed the tests order. 
- [https://github.com/ducktors/turborepo-remote-cache/issues/186](https://github.com/ducktors/turborepo-remote-cache/issues/186)
> feat(ABS): replace legacy azure-storage lib with @azure/storage-blob

- src/index.ts
- Bug fix (non-breaking change which fixes an issue)
Related: #366 
I have a library that is 3.3MB right now, and I kinda "arbitrarily" chose 50MB, but I figure if some build assets could include images, it may be good to bump further.
Any larger than that though, and... folks should probably statically host those images somewhere.
-------------
Alternatively, I see (in #366) there is a `BODY_LIMIT` environment variable -- must be a fastify thing 😅 
I was not able to find that in fastify's docs though?
> Raise the bodyLimit to 50MB from 1MB

- src/index.ts
- Bug fix (non-breaking change which fixes an issue)
The BODY_LIMIT env variable was being used in the content type parser, but not when creating the fastify app. This meant the practical body limit could not be raised past 50MB.
This PR uses the BODY_LIMIT var for both values.
> fix: Use BODY_LIMIT when creating app

- docs/custom-remote-caching.md
- Documentation Update
The latest versions of Turborepo [associate the **`teamslug`** property with the **`TURBO_TEAM`** environment variable](https://github.com/vercel/turborepo/blob/ac1eab9105534ac9c43fb6c403b651097375a3c3/crates/turborepo-lib/src/config/mod.rs#L224-L228), whereas `teamid` corresponds to `TURBO_TEAMID`. By setting and using `teamslug` within `.turbo/config.json`, we are able to utilize the Turborepo Remote Cache API without getting the `"querystring should have required property 'team'"` error message.
Additionally, I've updated the documentation to accurately reflect the lastest, expected Turborepo usage. Notably:
- Using **`--team`** instead of `--teamid` when providing the team as an argument
- [Turborepo does not accept …
> docs: update usage info within custom-remote-caching.md

- package.json
- pnpm-lock.yaml
- test/minio.ts
Updates `aws-sdk` to latest to patch GHSA-776f-qx25-q3cc.
From my monorepo where I implemented `turboerpo-remote-cache`, `npm audit` showed me this:
```
xml2js  <0.5.0
Severity: moderate
xml2js is vulnerable to prototype pollution - https://github.com/advisories/GHSA-776f-qx25-q3cc
fix available via `npm audit fix --force`
Will install turborepo-remote-cache@1.7.3, which is a breaking change
node_modules/xml2js
aws-sdk  <=2.1353.0
Depends on vulnerable versions of xml2js
node_modules/aws-sdk
turborepo-remote-cache  >=1.7.4
Depends on vulnerable versions of aws-sdk
services/turborepo-remote-cache/node_modules/turborepo-remote-cache
```
I also moved minio over to a separate port because running `pnpm run test` was causing intermittent failures between s3 and minio due to address in use …
> chore: update aws-sdk to patch GHSA-776f-qx25-q3cc

- src/plugins/remote-cache/storage/s3.ts
- Fixes issue on S3 `createWriteStream` where the process never actually reaches final to write the cache on the S3 storage; this causes turbobuild to throw timeout error when trying to write cache.
- The issue comes from latest change [to update aws-sdk to v3](https://github.com/ducktors/turborepo-remote-cache/pull/534) as part of issue https://github.com/ducktors/turborepo-remote-cache/issues/323
> fix: S3 - store upload promise early in order to complete createWriteStream
